#include <InternationalCountryCodes.hpp>
#include <Text.hpp>

#ifdef __MWERKS__
# pragma pcrelconstdata on
#endif

namespace ArsLexis{

    enum {
        countryAbbrevLength=3,
        countryNameLength=40, // 38+1 
    };
    
    typedef const char_t CountryAbbrevField_t[countryAbbrevLength];
    typedef const char_t CountryNameField_t[countryNameLength];
    
    struct CountryArrayEntry {
        const CountryAbbrevField_t abbrev;
        const CountryNameField_t name; 
    };
    
    static const CountryArrayEntry countries[]={
        {"AF", "Afghanistan, Islamic State of"},
        {"AL", "Albania"},
        {"DZ", "Algeria"},
        {"AS", "American Samoa"},
        {"AD", "Andorra, Principality of"},
        {"AO", "Angola"},
        {"AI", "Anguilla"},
        {"AQ", "Antarctica"},
        {"AG", "Antigua and Barbuda"},
        {"AR", "Argentina"},
        {"AM", "Armenia"},
        {"AW", "Aruba"},
        {"AC", "Ascension Island"},
        {"AU", "Australia"},
        {"AT", "Austria"},
        {"AZ", "Azerbaidjan"},
        {"BS", "Bahamas"},
        {"BH", "Bahrain"},
        {"BD", "Bangladesh"},
        {"BB", "Barbados"},
        {"BY", "Belarus"},
        {"BE", "Belgium"},
        {"BZ", "Belize"},
        {"BJ", "Benin"},
        {"BM", "Bermuda"},
        {"BT", "Bhutan"},
        {"BO", "Bolivia"},
        {"BA", "Bosnia-Herzegovina"},
        {"BW", "Botswana"},
        {"BV", "Bouvet Island"},
        {"BR", "Brazil"},
        {"IO", "British Indian Ocean Territory"},
        {"BN", "Brunei Darussalam"},
        {"BG", "Bulgaria"},
        {"BF", "Burkina Faso"},
        {"BI", "Burundi"},
        {"KH", "Cambodia, Kingdom of"},
        {"CM", "Cameroon"},
        {"CA", "Canada"},
        {"CV", "Cape Verde"},
        {"KY", "Cayman Islands"},
        {"CF", "Central African Republic"},
        {"TD", "Chad"},
        {"CL", "Chile"},
        {"CN", "China"},
        {"CX", "Christmas Island"},
        {"CC", "Cocos (Keeling) Islands"},
        {"CO", "Colombia"},
        {"KM", "Comoros"},
        {"CG", "Congo"},
        {"CD", "Congo, The Democratic Republic of the"},
        {"CK", "Cook Islands"},
        {"CR", "Costa Rica"},
        {"HR", "Croatia"},
        {"CU", "Cuba"},
        {"CY", "Cyprus"},
        {"CZ", "Czech Republic"},
        {"DK", "Denmark"},
        {"DJ", "Djibouti"},
        {"DM", "Dominica"},
        {"DO", "Dominican Republic"},
        {"TP", "East Timor"},
        {"EC", "Ecuador"},
        {"EG", "Egypt"},
        {"SV", "El Salvador"},
        {"GQ", "Equatorial Guinea"},
        {"ER", "Eritrea"},
        {"EE", "Estonia"},
        {"ET", "Ethiopia"},
        {"FK", "Falkland Islands"},
        {"FO", "Faroe Islands"},
        {"FJ", "Fiji"},
        {"FI", "Finland"},
        {"CS", "Former Czechoslovakia"},
        {"SU", "Former USSR"},
        {"FR", "France"},
        {"FX", "France (European Territory)"},
        {"GF", "French Guyana"},
        {"TF", "French Southern Territories"},
        {"GA", "Gabon"},
        {"GM", "Gambia"},
        {"GE", "Georgia"},
        {"DE", "Germany"},
        {"GH", "Ghana"},
        {"GI", "Gibraltar"},
        {"GB", "Great Britain"},
        {"GR", "Greece"},
        {"GL", "Greenland"},
        {"GD", "Grenada"},
        {"GP", "Guadeloupe (French)"},
        {"GU", "Guam (USA)"},
        {"GT", "Guatemala"},
        {"GG", "Guernsey"},
        {"GN", "Guinea"},
        {"GW", "Guinea Bissau"},
        {"GY", "Guyana"},
        {"HT", "Haiti"},
        {"HM", "Heard and McDonald Islands"},
        {"VA", "Holy See (Vatican City State)"},
        {"HN", "Honduras"},
        {"HK", "Hong Kong"},
        {"HU", "Hungary"},
        {"IS", "Iceland"},
        {"IN", "India"},
        {"ID", "Indonesia"},
        {"IR", "Iran"},
        {"IQ", "Iraq"},
        {"IE", "Ireland"},
        {"IM", "Isle of Man"},
        {"IL", "Israel"},
        {"IT", "Italy"},
        {"CI", "Ivory Coast (Cote D'Ivoire)"},
        {"JM", "Jamaica"},
        {"JP", "Japan"},
        {"JO", "Jordan"},
        {"KZ", "Kazakhstan"},
        {"KE", "Kenya"},
        {"KI", "Kiribati"},
        {"KW", "Kuwait"},
        {"KG", "Kyrgyz Republic (Kyrgyzstan)"},
        {"LA", "Laos"},
        {"LV", "Latvia"},
        {"LB", "Lebanon"},
        {"LS", "Lesotho"},
        {"LR", "Liberia"},
        {"LY", "Libya"},
        {"LI", "Liechtenstein"},
        {"LT", "Lithuania"},
        {"LU", "Luxembourg"},
        {"MO", "Macau"},
        {"MK", "Macedonia"},
        {"MG", "Madagascar"},
        {"MW", "Malawi"},
        {"MY", "Malaysia"},
        {"MV", "Maldives"},
        {"ML", "Mali"},
        {"MT", "Malta"},
        {"MH", "Marshall Islands"},
        {"MQ", "Martinique (French)"},
        {"MR", "Mauritania"},
        {"MU", "Mauritius"},
        {"YT", "Mayotte"},
        {"MX", "Mexico"},
        {"FM", "Micronesia"},
        {"MD", "Moldavia"},
        {"MC", "Monaco"},
        {"MN", "Mongolia"},
        {"MS", "Montserrat"},
        {"MA", "Morocco"},
        {"MZ", "Mozambique"},
        {"MM", "Myanmar"},
        {"NA", "Namibia"},
        {"NR", "Nauru"},
        {"NP", "Nepal"},
        {"NL", "Netherlands"},
        {"AN", "Netherlands Antilles"},
        {"NT", "Neutral Zone"},
        {"NC", "New Caledonia (French)"},
        {"NZ", "New Zealand"},
        {"NI", "Nicaragua"},
        {"NE", "Niger"},
        {"NG", "Nigeria"},
        {"NU", "Niue"},
        {"NF", "Norfolk Island"},
        {"KP", "North Korea"},
        {"MP", "Northern Mariana Islands"},
        {"NO", "Norway"},
        {"OM", "Oman"},
        {"PK", "Pakistan"},
        {"PW", "Palau"},
        {"PS", "Palestinian Territories"},
        {"PA", "Panama"},
        {"PG", "Papua New Guinea"},
        {"PY", "Paraguay"},
        {"PE", "Peru"},
        {"PH", "Philippines"},
        {"PN", "Pitcairn Island"},
        {"PL", "Poland"},
        {"PF", "Polynesia (French)"},
        {"PT", "Portugal"},
        {"PR", "Puerto Rico"},
        {"QA", "Qatar"},
        {"RE", "Reunion (French)"},
        {"RO", "Romania"},
        {"RU", "Russian Federation"},
        {"RW", "Rwanda"},
        {"GS", "S. Georgia &amp; S. Sandwich Isls."},
        {"SH", "Saint Helena"},
        {"KN", "Saint Kitts &amp; Nevis Anguilla"},
        {"LC", "Saint Lucia"},
        {"PM", "Saint Pierre and Miquelon"},
        {"ST", "Saint Tome (Sao Tome) and Principe"},
        {"VC", "Saint Vincent &amp; Grenadines"},
        {"WS", "Samoa"},
        {"SM", "San Marino"},
        {"SA", "Saudi Arabia"},
        {"SN", "Senegal"},
        {"SC", "Seychelles"},
        {"SL", "Sierra Leone"},
        {"SG", "Singapore"},
        {"SK", "Slovak Republic"},
        {"SI", "Slovenia"},
        {"SB", "Solomon Islands"},
        {"SO", "Somalia"},
        {"ZA", "South Africa"},
        {"KR", "South Korea"},
        {"ES", "Spain"},
        {"LK", "Sri Lanka"},
        {"SD", "Sudan"},
        {"SR", "Suriname"},
        {"SJ", "Svalbard and Jan Mayen Islands"},
        {"SZ", "Swaziland"},
        {"SE", "Sweden"},
        {"CH", "Switzerland"},
        {"SY", "Syria"},
        {"TJ", "Tadjikistan"},
        {"TW", "Taiwan"},
        {"TZ", "Tanzania"},
        {"TH", "Thailand"},
        {"TG", "Togo"},
        {"TK", "Tokelau"},
        {"TO", "Tonga"},
        {"TT", "Trinidad and Tobago"},
        {"TN", "Tunisia"},
        {"TR", "Turkey"},
        {"TM", "Turkmenistan"},
        {"TC", "Turks and Caicos Islands"},
        {"TV", "Tuvalu"},
        {"UM", "USA Minor Outlying Islands"},
        {"UG", "Uganda"},
        {"UA", "Ukraine"},
        {"AE", "United Arab Emirates"},
        {"UK", "United Kingdom"},
        {"US", "United States"},
        {"UY", "Uruguay"},
        {"UZ", "Uzbekistan"},
        {"VU", "Vanuatu"},
        {"VE", "Venezuela"},
        {"VN", "Vietnam"},
        {"VG", "Virgin Islands (British)"},
        {"VI", "Virgin Islands (USA)"},
        {"WF", "Wallis and Futuna Islands"},
        {"EH", "Western Sahara"},
        {"YE", "Yemen"},
        {"YU", "Yugoslavia"},
        {"ZR", "Zaire"},
        {"ZM", "Zambia"},
        {"ZW", "Zimbabwe"}    
};

    static inline uint_t countriesCount()
    {
        return sizeof(countries)/sizeof(countries[0]);
    }

    int getInternationalCountryCodesCount()
    {
        return countriesCount();
    }

    void getInternationalCountryName(int pos, String& nameOut)
    {   
        assert(pos >= 0 && pos < countriesCount());
        nameOut.assign(countries[pos].name);
    }

    void getInternationalCountryCode(int pos, ArsLexis::String& symbolOut) 
    {
        assert(pos >= 0 && pos < countriesCount());
        symbolOut.assign(countries[pos].abbrev);
    }
    
    // always return index value in (0, statesCount-1)   
    int getInternationalCountryIndexByFirstChar(ArsLexis::char_t inChar)
    {
        inChar = ArsLexis::toLower(inChar);
        for (int i = 0; i < countriesCount(); i++)
        {
            char_t foundChar = ArsLexis::toLower(countries[i].name[0]);
            if (inChar <= foundChar)
                return i;
        }
        return countriesCount()-1;
    }    
} 
