#include "iPediaForm.hpp"
#include "SysUtils.hpp"

bool iPediaForm::handleEvent(EventType& event)
{
    bool handled=false;
    switch (event.eType)
    {
        case winDisplayChangedEvent:
            // workaround for PalmOS bug - when winDisplayChangedEvent is generated by PalmOS<5.4 it contains only rubbish.
            ArsLexis::getScreenBounds(event.data.winDisplayChanged.newBounds); 
            resize(event.data.winDisplayChanged.newBounds);
            break;
    
        default:
            handled=Form::handleEvent(event);
    }
    return handled;
}

Err iPediaForm::initialize()
{
    iPediaApplication& app=static_cast<iPediaApplication&>(application());
    Err error=Form::initialize();
    if (!error && app.diaSupport().available())
        app.diaSupport().configureForm(*this, 160, pinMaxConstraintSize, pinMaxConstraintSize, 160, pinMaxConstraintSize, pinMaxConstraintSize);
    return error;
}
