#include "iPediaForm.hpp"
#include "SysUtils.hpp"

Boolean iPediaForm::handleEvent(EventType& event)
{
    Boolean handled=false;
    switch (event.eType)
    {
        case winDisplayChangedEvent:
            // workaround for PalmOS bug - when winDisplayChangedEvent is generated by PalmOS<5.4 it contains only rubbish.
            ArsLexis::getScreenBounds(event.data.winDisplayChanged.newBounds); 
            resize(event.data.winDisplayChanged.newBounds);
            break;
    
        default:
            handled=Form::handleEvent(event);
    }
    return handled;
}